### ISSUE TITLE
Django Buildpack doesn't allow you to exec python commands

### ISSUE THREAD

**Issue by jcampbell05** [hashicorp/waypoint#936] opened 2020-12-19 13:02 UTC
**Describe the bug**

When using a python buildpack "python" points to python2 and "python3" is unaware of your installed packages". However using this via heroku it works.

**Steps to Reproduce**
Setup a python application using buildpacks and notice that python commands wont work via "exec"

**Expected behavior**
You should be able to use python just like you can via the Procfile

**Comment by briancain** [comment] 2021-03-11 22:26
Hey there @jcampbell05 - Can you provide us with an example project with a waypoint.hcl that reproduces this issue? If it's simpler, one of the projects from [waypoint-examples](https://github.com/hashicorp/waypoint-examples) might be easiest. For example, the docker/go/python one might be best.Thanks!

**Comment by briancain** [comment] 2021-06-03 21:06
Hey there @jcampbell05 - I haven't been able to reproduce this issue, and since it's been a while since we've heard from you, I'm going to go ahead and close this issue. If you are still experiencing a problem, please feel free to respond to this issue with the requested information or open a new issue. Thank you! 😄

**Closed by briancain** 2021-06-03 21:06 UTC
Labels: bug, plugin/pack, waiting-reply
