### ISSUE TITLE
Message: unknown key: invalid authentication token

### ISSUE THREAD

**Issue by cmoulliard** [hashicorp/waypoint#726] opened 2020-10-29 08:36 UTC
## Issue

A grpc call issued against the server launched locally got the following error even if a token is provided

```
waypoint token new
TOKEN=bM152PWkXxfoy4vA51JFhR7LoxtyFCXcRQSwivgatqT2rZAVysoSUGYa8z7Knjan438Tz4poUNemJ65S7XEZBxmbFchyZUKQFSApY
grpcurl -insecure -H "client-api-protocol: 1,1" -H "Authorization: $TOKEN" localhost:9701 hashicorp.waypoint.Waypoint.ListWorkspaces
ERROR:
  Code: Unknown
  Message: unknown key: invalid authentication token
```

This error happens here within the code
![Screenshot 2020-10-29 at 08 52 08](https://user-images.githubusercontent.com/463790/97540767-65f87c00-19c4-11eb-93a4-27988440cf50.png)

Code : https://github.com/hashicorp/waypoint/blob/22850d0530f8c71fa244854093734f07dbe053de/internal/server/singleprocess/auth.go#L69

**Steps to Reproduce**

- Open this project under intellij or visualcode
- Launch the server using these args `server run -accept-tos -vvv -db=data.db -listen-grpc=0.0.0.0:9701 -listen-http=0.0.0.0:9702`
- execute the grpc call

**Comment by mitchellh** [comment] 2020-10-30 15:23
Is the server bootstrapped? I'm able to use grpcurl locally without an issue. 

One thing: the header has to be lower cased. I don't remember why that is but I think the conversion of headers => metadata in the gRPC library itself lowercases them.

**Comment by cmoulliard** [comment] 2020-11-02 08:19
> Is the server bootstrapped?

Server is started. What do you mean by `bootstrapped` ?

**Comment by mitchellh** [comment] 2020-11-18 18:37
Sorry missed your response. On first startup, the server should output a message about requiring a bootstrap (to get your first auth token). If it isn't bootstrapped, API calls won't work. The startup message will output a CLI command to get this done. See: https://www.waypointproject.io/docs/server/run#bootstrap-the-server

**Comment by briancain** [comment] 2021-02-18 22:48
Hey there @cmoulliard - I've tried this recently and cannot reproduce the issue mentioned. Since it's been a while since we've heard back from you, I'll go ahead and close this issue. However if you're able to still reproduce this using the latest version of Waypoint (at the moment, version 0.2.2) feel free to open a new issue so we can take a look. Thank you!

**Closed by briancain** 2021-02-18 22:48 UTC
Labels: waiting-reply

**Comment by rayko92** [comment] 2021-02-27 00:05
Hi! I got the same error.

I'm using Waypoint installed via `waypoint install` in Nomad. Here is the command.

```
waypoint install -platform=nomad \
-nomad-dc=general \
-nomad-region=dc1 \
-nomad-namespace=default\
-nomad-annotate-service="traefik.enable=true" \
-accept-tos
```
Error in UI:

![image](https://user-images.githubusercontent.com/7152452/109367478-7fd49d80-7896-11eb-98ad-0f76fb4b4bcb.png)

Error in stderr:

```
2021-02-26T23:49:13.919Z [INFO]  waypoint.server.grpc: /hashicorp.waypoint.Waypoint/ListProjects response: error="bad signature: invalid authentication token" duration=82.569µs

2021-02-26T23:49:13.920Z [INFO]  waypoint.server.http: HTTP request: POST /hashicorp.waypoint.Waypoint/ListProjects: date=2021-02-26T23:49:13.919666764Z http.host=10.10.0.6:9702 http.method=POST http.request_path=/hashicorp.waypoint.Waypoint/ListProjects http.remote_addr=10.10.0.7 http.response_size=0 http.scheme= http.status_code=200 http.useragent="<user agent>" http.version=HTTP/1.1
```

Error in GitLab CI/CD:

![image](https://user-images.githubusercontent.com/7152452/109367646-ec4f9c80-7896-11eb-9f4f-861c70145494.png)

The token was I use is created using `waypoint token new`

![image](https://user-images.githubusercontent.com/7152452/109367746-3c2e6380-7897-11eb-92f0-f61d3af671b3.png)

If you need to create a new issue from this, please let me know.

Thanks!

**Comment by rayko92** [comment] 2021-02-27 11:50
I'm tryin to make a workaround or something. If I delete the data.db, recreate it and bootstrap the server manually, works fine every token.

**Comment by briancain** [comment] 2021-03-01 22:08
Hey @rayko92 - This looks like it might be a different error. The original issue is about an error occurring when running `waypoint token new`, where as it looks like you are getting an error about the token but in a different context using waypoint. I recommend opening a new issue and filling out all the requested information + whatever else is relevant to the reproduction. Thanks :)
