### ISSUE TITLE
Add method to configure custom project properties

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/waypoint#1368] opened 2021-04-21 06:16 UTC
**Is your feature request related to a problem? Please describe.**

We have potential plugins that could control service links and datastore credentials but would have to come up with some external service to store what those links etc. are. Having it built into Waypoint would decrease the number of services a developer needs to touch in order to configure an app.

**Describe the solution you'd like**

It would be great if there was a command like

```
waypoint properties
```

This would implement the following subcommands:

- `get <namespace> <key>`: get a property in a namespace
- `set <namespace> <key> <value>`: set a property in a namespace
- `delete <namespace> <key>`: delete a property in a namespace
- `clear [<namespace>]`: clear all properties all or just within an optionally specified namespace)
- `export [<namespace>]`: export a key=value list of all properties, optionally within the specified namespace

Properties would be stored in a new `propertysourcer` type, which plugins could implement as they wish.

**Describe alternatives you've considered**

Each custom plugin could have an alternative datastore maintained by the company deploying waypoint. This would have a different CLI/UI from Waypoint, increasing cognitive overhead for developers attempting to manage their own systems.

**Explain any additional use-cases**

A given `ReleaseManager` might manage traefik for routing, and would enable routing based on some config that isn't stored in the job (as labels or whatever). We'd want that plugin to be able to ingest the properties and decide how to configure itself. For instance, one might imagine something like [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy), which configures proxy configs based on container labels. We'd probably store something similar for apps and use that to allow developers to handle external proxying with waypoint.

**Additional context**

As we investigate Waypoint for deployments, one goal we have is to centralize the number of places a developer needs to go to manage their service. Having the waypoint cli be a one-stop shop for this would make it much easier for our developers to grok than what we currently have.

**Comment by krantzinator** [comment] 2021-04-21 15:22
Can you provide some more clarity on the problem that your proposed solution would solve? Maybe a specific example use case?

**Comment by josegonzalez** [comment] 2021-04-22 05:14
At SeatGeek, each repository has an `env.hcl` file. This file is used to control the following types of app config:

- secrets (from vault)
- static values (dunno why we didnt just tell devs to set these in code)
- service links (constructed urls pointing at services in consul)
- datastores (backed by vault creds)
- consul kv (for less secretive things)

At deploy time, our Nomad deployment tooling ingests this file and creates a `.env` template for Nomad that is then used for environment variables.

If we were to move to waypoint, we would have no way to specify service links or datastores. Each of these has a variable url depending on the environment (though I suppose we could use alternative TLDs through consul and have something common that each env supports) and the datastores have some weird template that we'd need to use in addition to that.

My idea here would be to have these be part of a custom `ReleaseManager` or something. This `ReleaseManager` would allow developers to do something like:

```
waypoint properties set datastore DATABASE_URL db-api
```

And then the ReleaseManager would turn around and know that it needs to inject a custom template for the datastore link.

In the above scenario, we would have a custom ReleaseManager for Nomad - we'd need one anyways to add support for other properties in Nomad - which would be able to interpret anything in the `datastore` namespace.

**Comment by evanphx** [comment] 2021-04-28 17:01
@josegonzalez Hiya! Could you tell us a bit more about why `waypoint config` doesn't fit your needs.

**Comment by josegonzalez** [comment] 2021-04-29 23:22
I think my concern with `waypoint config` is that it is used normally as an env var store vs a generic property store. Potentially `waypoint config` could be _backed by_ `waypoint properties`, and just exposed to users under a separate command.

My alternative is to use `waypoint config` but with some patterns on top of the key naming - can config keys have `.` or `:` characters? - that can then be extracted by other tools.

**Comment by evanphx** [comment] 2021-04-29 23:25
@josegonzalez That's all true, but I guess what we're not seeing is why you need a generic property store rather than the functionality `waypoint config` provides. What would be reading these properties? apps? How?

**Comment by evanphx** [comment] 2021-06-23 17:12
Hey there,

I am going to close this because we feel that the upcoming Variables work will likely satisfy your needs. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Closed by evanphx** 2021-06-23 17:12 UTC
Labels: core, enhancement, waiting-reply
