### ISSUE TITLE
waypoint install with -context-create creates an incorrect context

### ISSUE THREAD

**Issue by 1xyz** [hashicorp/waypoint#2973] opened 2022-02-03 01:23 UTC
**Describe the bug**
the `waypoint install` with -context-create creates an incorrect context. (see repro steps)

**Steps to Reproduce**
```shell
# 0) clean up config 
$ rm -rf $HOME/.config/waypoint

# 1) create a remote context
$ waypoint context create -server-addr=ec2-35....compute.amazonaws.com:9701 -server-auth-token=....
 -server-require-auth=true  -server-tls-skip-verify -set-default remote

# 2) start new local server with  context local
$ waypoint install -accept-tos -context-create=local -platform=docker
...
Advertise Address: waypoint-server:9701
Web UI Address: https://localhost:9702

# 3) the context list, my local context pointing to my remote ec2 server.
$ waypoint context list
    |  NAME  | PLATFORM |                    SERVER ADDRESS
----+--------+----------+--------------------------------------------------------
  * | local  | n/a      | ec2-35....compute.amazonaws.com:9701
    | remote | n/a      | ec2-35.....compute.amazonaws.com:9701
    
 Expected: local context to point to   localhost:9701 and not my remote ec2 instance

$ waypoint version
CLI: v0.7.1 (062857d16)
Server: v0.7.1
```

**Expected behavior**
 Expected: local context to point to   localhost:9701 and not my remote ec2 instance

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version:
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`)
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

**Additional context**

**Comment by catsby** [comment] 2022-02-03 23:35
Hello there - this is very strange as I'm unable to reproduce it myself. One thing I do notice is that the `Platform` for your `local` context is listed as `n/a`, where as it should be `docker` like mine below. I'll ask internally if anyone else can reproduce this. In the meantime, can you tell me your operating system, and how you're running Docker? For example I'm macOS and running Docker with the Docker for Mac app. 

Thanks!

Output:

```console
[waypoint][main](4)$ waypoint version
CLI: v0.7.1 (062857d16)

[waypoint][main](4)$ waypoint context create \
  -server-addr=ec2-54-*******.amazonaws.com:9701 \
  -server-auth-token="******" \
  -server-require-auth=true  \
  -server-tls-skip-verify \
  -set-default remote
Context "remote" created.

[waypoint][main](4)$ waypoint context list
    |  NAME  | PLATFORM |                     SERVER ADDRESS
----+--------+----------+---------------------------------------------------------
  * | remote | n/a      | ec2-54-*******.amazonaws.com:9701

[waypoint][main](4)$ waypoint install -accept-tos -context-create=local -platform=docker
✓ Pulling image: hashicorp/waypoint:latest
 │ 59bf1c3509f3: Already exists
 │ 88d1accf2ff1: Downloading [>                                                  ]
 │  73.21kB/7.08MBulling fs layer
 │ 88d1accf2ff1: Pull complete
 │ aabf21bf4aef: Pull complete
 │ 5d8d0618dcd7: Pull complete
 │ d22a07f89277: Pull complete
 │ f64b14d5fa70: Pull complete
 │ Digest: sha256:2fdfedac99f412a14dc33fcc81d0759ff34185e62c662ce7f3e88777a42427d4
 │ Status: Downloaded newer image for hashicorp/waypoint:latest
✓ Installing Waypoint server to docker
✓ Server container started!
✓ Server installed and configured!
✓ Successfully connected to Waypoint server in Docker!
✓ Installing runner...
✓ Registered ondemand runner!
✓ Waypoint runner installed and started!
Waypoint server successfully installed and configured!

The CLI has been configured to connect to the server automatically. This
connection information is saved in the CLI context named "local".
Use the "waypoint context" CLI to manage CLI contexts.

The server has been configured to advertise the following address for
entrypoint communications. This must be a reachable address for all your
deployments. If this is incorrect, manually set it using the CLI command
"waypoint server config-set".

To launch and authenticate into the Web UI, run:
waypoint ui -authenticate

Advertise Address: waypoint-server:9701
Web UI Address: https://localhost:9702

[waypoint][main](4)$ waypoint context list
    |  NAME  | PLATFORM |                     SERVER ADDRESS
----+--------+----------+---------------------------------------------------------
  * | local  | docker   | localhost:9701
    | remote | n/a      | ec2-54-*******.amazonaws.com:9701

[waypoint][main](4)$ waypoint version
CLI: v0.7.1 (062857d16)
Server: v0.7.1

```

**Comment by 1xyz** [comment] 2022-02-04 19:39
Hello @catsby  the setup is docker on macos. 

```shell
$ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

fwiw from the behavior that I see, I *"think"* the new "local" context created is for some reason copying the existing one.

Thanks!

**Comment by 1xyz** [comment] 2022-02-04 19:58
@catsby, i tried the orig. repro step(s) and it does not reproduce the bug anymore. Over the last day, we've restarted the remote waypoint server, the local docker desktop app. One of those *might* have made the bug go away

```shell
waypoint context list
    |  NAME  | PLATFORM |                    SERVER ADDRESS
----+--------+----------+--------------------------------------------------------
  * | local  | docker   | localhost:9701
    | remote | n/a      | ec2-35-.....us-west-2.compute.amazonaws.com:9701
 ```

Thanks!

**Comment by xiaolin-ninja** [comment] 2022-02-09 18:19
Looks like nobody can reproduce this issue, we'll close this for now. Please make a new issue if it comes up again!

**Closed by xiaolin-ninja** 2022-02-09 18:19 UTC
Labels: core/install
