### ISSUE TITLE
"waypoint up" deployment stage fails for secound deploy

### ISSUE THREAD

**Issue by matyaskov** [hashicorp/waypoint#1231] opened 2021-03-24 22:45 UTC
**Describe the bug**
I'm trying to deploy the [docker/nodejs waypoint example application](https://github.com/hashicorp/waypoint-examples/blob/93ed0e8baf68a0dc641af34c9a81b18556b97a06/docker/nodejs/waypoint.hcl) to localhost Docker. However "waypoint up" no longer works for the second run. CLI says that "unable to start Docker container: Error response from daemon: driver failed" and " Bind for 0.0.0.0:3000 failed: port is already allocated" I guess waypoint up should be able to handle this situation, remove the container and spin up a new one.

**Steps to Reproduce**
$ git clone https://github.com/hashicorp/waypoint-examples.git
$ git checkout 439e6699a6bb801613b59157d7f229580890c4d2
$ cd waypoint-examples/docker/nodejs
$ waypoint install --platform=docker -accept-tos
$ waypoint init
$ waypoint up

Changing the waypoint-examples/docker/nodejs/views/pages/index.ejs file 

$ waypoint up (output: https://gist.github.com/matyaskov/1195fe1ebca8f3dcc4dccad12def3da5)

and here I get the error message:
"unable to start Docker container: Error response from daemon: driver failed" and " Bind for 0.0.0.0:3000 failed: port is already allocated"

console output: https://gist.github.com/matyaskov/1195fe1ebca8f3dcc4dccad12def3da5
waypoint.hcl: https://gist.github.com/matyaskov/e175e338b4c78f6faa084ba0d6c04d56

**Expected behavior**
I would expect a seamless deployment for 2nd attempt as well waypoint shuts down the application and starts the new version and where there's no port allocation issue.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: Waypoint v0.2.3 (e0128167)
* Waypoint Server Platform and Version: docker
* Waypoint Plugin: pack

**Additional context:**

**OS:**
MacOS BigSur 11.2.1 (20D75)

**Docker version:**

Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by briancain** [comment] 2021-03-24 22:57
Hey there @matyaskov ! Thanks for the detailed report, we appreciate it!

This is actually a bug that was fixed in the most recent release of Waypoint version 0.2.4: https://www.waypointproject.io/downloads

It was fixed via this revert, because the original patch caused the regression: https://github.com/hashicorp/waypoint/pull/1189

Upgrading to the latest version of Waypoint should solve your issue though. Thanks again! 😄

**Closed by briancain** 2021-03-24 22:57 UTC
