### ISSUE TITLE
The latest version waypoint doesn’t want deploy the ECS app

### ISSUE THREAD

**Issue by psihachina** [hashicorp/waypoint#2240] opened 2021-09-07 19:50 UTC
**Describe the bug**
The latest version waypoint doesn’t want to deploy the ECS app

**Steps to Reproduce**
`waypoint up -app hamster -var-file waypoint.wpvars`

https://gist.github.com/psihachina/f566b712411f7669472c6ac29fbb7349

**Expected behavior**
Successful command complition 

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: v0.2.0-3147-g6b5047dd (6b5047dd)
* Waypoint Server Platform and Version: `ecs`,  v0.5.1
* Waypoint Plugin: `aws/ecs`

**Additional context**
I also tried reinstalling the server, but that doesn't help.

**Comment by briancain** [comment] 2021-09-07 20:56
Hey there @psihachina! Based on the CLI version you specified, I have to wonder if that's the root cause? Version 0.2.0 is pretty old at this point. I assume you might be building the Waypoint CLI yourself? Either way, I recommend trying to purge the waypoint CLI from your path just to make sure all old instances are gone, (i.e. eventually running `waypoint` results in command not found), then try rebuilding the waypoint CLI or directly install the [latest version from our website](https://www.waypointproject.io/downloads).

If you are still receiving the same issue on the 0.5.2+ CLI version please let us know.  Thank you!

**Comment by psihachina** [comment] 2021-09-08 08:05
Hi, @briancain 

The problem was with my fork. I synchronized it with GitHub and for some reason, the cli waypoint was not updating due to this. Synchronized with git CLI and everything is fine. But the problem with the deployment remains. Version CLI when I building the Waypoint: v0.5.0-406-g3903c728 (3903c728). When I directly install the latest version from the website everything fine - version 0.5.1 and successfully deploy.

**Comment by briancain** [comment] 2021-09-08 15:23
@psihachina When you use a CLI built off `main`, are you also using a Waypoint server built off `main`? It's possible there's something odd between using a released 0.5.1 server and a custom built Waypoint CLI off `main` 🤔 

Either way, could you include the Waypoint server logs? The logs show the local runner CLI, but I'm guessing the error probably exists on the server logs based on this:

> » Deploying...
> ! error reading from server: EOF

Thank you!

**Comment by psihachina** [comment] 2021-09-08 16:16
@briancain  https://gist.github.com/psihachina/ca547123f2224472424886c93857d3cb

**Comment by briancain** [comment] 2021-09-08 17:09
Hey there @psihachina - So the error itself is coming from the server, which looks to be a config issue:

```
| 1631115997783 | panic: unknown scope                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 1631115997783 | goroutine 1267 [running]:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 1631115997783 | github.com/hashicorp/waypoint/internal/server/singleprocess/state.(*State).configVarId(0xc0008c22c0, 0xc000593740, 0xc0000f1b48, 0xffffffffffffffff, 0x0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 1631115997783 |  /tmp/wp-src/internal/server/singleprocess/state/config.go:376 +0x52a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 1631115997783 | github.com/hashicorp/waypoint/internal/server/singleprocess/state.(*State).configSet(0xc0008c22c0, 0xc000dceb60, 0xc000dfacd0, 0xc000593740, 0x3094120, 0xc000c63638)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 1631115997783 |  /tmp/wp-src/internal/server/singleprocess/state/config.go:72 +0x3c         
```

https://github.com/hashicorp/waypoint/blob/91ac77d77149a4cf5fd5e8877b56e9c99c5eeae8/internal/server/singleprocess/state/config.go#L168-L170

There's a lot of work currently happening around configs on `main`, and it's very likely that things are going to break while you are building a custom CLI. I recommend staying off `main` for now if you're going to use a released version of Waypoint server. Or be prepared for breakage every now and then for the next few weeks while this work is ongoing. Typically I get around this by always building my own Waypoint server and CLI so both point at the same version.

**Comment by psihachina** [comment] 2021-09-08 18:03
Hi @briancain,


Thanks for the answers. I followed your advice and it helped. I synchronized the CLI and the server based on `main` one and everything worked.

**Comment by briancain** [comment] 2021-09-08 18:23
Excellent! I'll go ahead and close this issue! Glad you were able to get back to a working state.

**Closed by briancain** 2021-09-08 18:23 UTC
Labels: bug, question
