### ISSUE TITLE
Waypoint getting started for kind cluster doesn't work

### ISSUE THREAD

**Issue by girikuncoro** [hashicorp/waypoint#531] opened 2020-10-16 09:30 UTC
**Describe the bug**
Running `waypoint install --platform=kubernetes -accept-tos` on kind cluster doesn't work, shows below error:
```
$ waypoint install --platform=kubernetes -accept-tos
service/waypoint created
statefulset.apps/waypoint-server created
! Error waiting for service ready: timed out waiting for the condition

  The Waypoint server has been deployed, but due to this error we were
  unable to automatically configure the local CLI or the Waypoint server
  advertise address. You must do this manually using "waypoint context"
  and "waypoint server config-set".
```

**Steps to Reproduce**
Follow the steps to Deploy Waypoint application to kubernetes (the kind cluster) on [hashicorp learn](https://learn.hashicorp.com/tutorials/waypoint/get-started-kubernetes?in=waypoint/get-started-kubernetes)

**Expected behavior**
`waypoint install` should work properly for kind cluster. I haven't dig deep but probably this might be caused by pending External IP LoadBalancer service (in kind cluster LoadBalancer External IP never gets allocated because of local machine)

**Comment by bhops** [comment] 2020-10-16 14:30
I was able to get this working by doing the following after this failure:
```bash
kubectl port-forward svc/waypoint 9701:9701

# open a separate terminal
waypoint server bootstrap -server-addr=127.0.0.1:9701 -server-tls-skip-verify
# then using the provided token
waypoint context create -server-addr=127.0.0.1:9701 -server-tls-skip-verify -server-auth-token=$TOKEN kind
```

**Comment by mitchellh** [comment] 2020-10-16 16:17
I think a dupe of #537

**Closed by mitchellh** 2020-10-16 16:17 UTC

**Comment by mvz** [comment] 2020-10-16 17:16
@mitchellh I think #537 is different since that problem occurs at a later step in the tutorial.

**Comment by mitchellh** [comment] 2020-10-16 17:22
Sorry I meant https://github.com/hashicorp/waypoint/issues/527 :)
